### ISSUE TITLE
password hashing

### ISSUE THREAD

**Issue by EyobDejene** [EyobDejene/TechTeam#26]

**Comment by OlafDs** [comment]
UPDATE: Password is now legit being hashed in the database 👽👽👽

The hashing code is in the 'users.model.js' file in the map 'models'

**Comment by OlafDs** [comment]
![1b19abf86795408ae21c9c2d665704f3](https://user-images.githubusercontent.com/49676649/59553772-4660df00-8f9a-11e9-80ec-a061aeb2a36f.png)

**Comment by CountNick** [comment]
Good job!:clown_face:

**Comment by EyobDejene** [comment]
Hasing is working!

**Comment by EyobDejene** [comment]
Im trying to login but it doesn't work, maybe because the passwords are now been hashed when registering.

**Comment by OlafDs** [comment]
@EyobDejene I will take a look and try to fix the problem 👍

**Comment by OlafDs** [comment]
Update: I figured it out why the login doesn't work. Hashing works only one way and thats to hash the password in the database. You cant decrypt the password. If we want to do that we need encryption code and not hashing code. With encryption it works two ways: you can encrypt your password en decrypt your password. So i will look further if we can use that.

**Comment by EyobDejene** [comment]
Nice research work!

**Comment by superstephan1** [comment]
Looking good now guys! i'll close the issue
