### ISSUE TITLE
Where can i store images for the wiki

### ISSUE THREAD

**Issue by CountNick** [EyobDejene/TechTeam#32]
Anyone suggestions on what the best place for wiki images would be?

**Comment by CountNick** [comment]
Also made a start on Github Workflow doc in wiki, and some other docs in the wiki. Would be great if you guys looked into it.:clown_face:

**Comment by OlafDs** [comment]
@CountNick Maybe store it in a issue or in another page calles "Photos"? Maybe someone else has a better idea 🤡 

And i will check the wiki! I'm also going to make a start in the wiki 🏃 💨

**Comment by EyobDejene** [comment]
Maybe you can store them on the oege server

**Comment by superstephan1** [comment]
You could upload the images to https://imgur.com/ and link them in the wiki

**Comment by robert-hoekstra** [comment]
I used to make a folder in the Git Repo where I dropped all my images.

**Comment by superstephan1** [comment]
I think enough solutions are named! i'll close the issue now.

**Comment by CountNick** [comment]
I'm storing images on imgur.com
