### ISSUE TITLE
Image upload bug

### ISSUE THREAD

**Issue by robert-hoekstra** [EyobDejene/TechTeam#33]
# Image and bio upload bug
When changing your bio your avatar changes

## How to reproduce

1. - Create a new account
2. - upload an image to your account and save changes
3. - Change your bio (which is not the same as the bio I wrote during registration)
4. - Press Save
5. - Your picture has now been changed to a random image

**Comment by CountNick** [comment]
Did you fix this already?

**Comment by CountNick** [comment]
How i love al these avatar bufs :bug: 🤡, going to look into this rn

**Comment by CountNick** [comment]
![Schermafbeelding 2019-06-16 om 16 53 35](https://user-images.githubusercontent.com/47485018/59565740-6c988480-9057-11e9-9dd6-2b685a88f05c.png)

**Comment by CountNick** [comment]
@EyobDejene @robert-hoekstra @OlafDs @superstephan1  Does someone know what i'm doing wrong? If filename is undefined avatar should be the current string that's saved on the db, but i can't seem to figure it out... Should be a simple fix tho:see_no_evil:

**Comment by CountNick** [comment]
@superstephan1 Thanks for helping me fix this :bug:
