### ISSUE TITLE
explore function

### ISSUE THREAD

**Issue by EyobDejene** [EyobDejene/TechTeam#4]
# Summary of what i did 🛠
* Added in the home route a function to get data from mogodb instead of using static data 🔀
* Added a check if the request is a xhr request 🔀
* Added in the front-end a refresh button to refresh randomly new people 🔀 
* Added Additional CSS💄

# :neckbeard: It's now possible for users to:
* refresh button to explore new people nearby on skill level based✨

**Comment by superstephan1** [comment]
Sick! Refresh working nicely with user collection data!
